# =============================================================================
# Module 3: TOM Calculation & Cytoscape Network Export
# 22q13 / Phelan-McDermid Syndrome WGCNA Pipeline
#
# Description: Computes the global Topological Overlap Matrix (TOM) from the
#              expression data, exports per-module edge/node files for Cytoscape,
#              and (if Cytoscape is running) builds disease-stratified networks
#              via RCy3.
#
# Usage:
#   Rscript 03_export_network.R <network_objects.rds> <output_dir>
#
# Arguments:
#   network_objects.rds : Output of Module 2
#   output_dir          : Directory to write outputs
#
# Outputs (written to output_dir/):
#   cytoscape_files/    : Per-module CytoscapeInput-edges-*.txt and
#                         CytoscapeInput-nodes-*.txt files
#   tom_objects.rds     : TOM matrix + modTom for downstream ranking module
#
# *** IMPORTANT — Cytoscape requirement ***
# The createNetworkFromDataFrames / createDegreeFilter / createColumnFilter
# calls require a running Cytoscape desktop application (v3.9+) on the same
# machine. These steps CANNOT run inside a headless Docker container.
# Pass --skip_cytoscape TRUE to the Nextflow pipeline to bypass them.
# All edge/node file export steps run fully headless.
#
# Fixes applied vs original script:
#   - Flag 1: final$gene_symbol → final$Gene_symbol (case correction)
#   - Flag 4: ASD_PMS column replaced with ASD == 1 & PMS == 1 filter
#   - Flag 8: createCompositeFilter() given filter.name + filter.list arguments
# =============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(WGCNA)
  library(tidyr)
  library(stringr)
  library(matrixStats)
  # RCy3 is loaded only when skip_cytoscape = FALSE (requires running Cytoscape)
})

options(stringsAsFactors = FALSE)

# ---------------------------------------------------------------------------
# Parse command-line arguments
# ---------------------------------------------------------------------------
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) {
  stop("Usage: Rscript 03_export_network.R <network_objects.rds> <output_dir>",
       call. = FALSE)
}
network_objects_file <- args[1]
output_dir           <- args[2]
skip_cytoscape       <- if (length(args) >= 3) as.logical(args[3]) else FALSE

cytoscape_dir <- file.path(output_dir, "cytoscape_files")
dir.create(cytoscape_dir, recursive = TRUE, showWarnings = FALSE)

message("=== Module 3: TOM Calculation & Cytoscape Export ===")

# ---------------------------------------------------------------------------
# Load objects from Module 2
# ---------------------------------------------------------------------------
obj          <- readRDS(network_objects_file)
datExpr      <- obj$datExpr
datExpr1     <- obj$datExpr1
genedata     <- obj$genedata
moduleColors <- obj$moduleColors
moduleLabels <- obj$moduleLabels
MEs          <- obj$MEs
colors       <- obj$colors
nGenes       <- obj$nGenes
final        <- obj$final
gene         <- obj$gene

# ---------------------------------------------------------------------------
# Creating Topology matrix from data based on Similarity
# NOTE: This step can take significant time/memory for large gene sets.
# ---------------------------------------------------------------------------
adjacency = adjacency(datExpr, power = 9)

# Turn adjacency into topological overlap
TOM = TOMsimilarity(adjacency)

dissTOM = 1-TOM

ensembl_match = is.finite(match(final$Ensembl,colnames(datExpr)))

final = final[ensembl_match,]

colnames(final) = c("Ensembl","Gene_symbol","ASD","I_D","Seizures","Hypotonia","Lang_Imp","PMS","mlabel","mcolor")
final$total = final$ASD + final$I_D + final$Hypotonia + final$Seizures + final$Lang_Imp + final$PMS
final = final[!(final$total == 0),]
final[final$PMS == 1,]
# Create empty node and edge file for consolidated nodes and edges generated by color module
node_final = data.frame(id = character(),
                        altName = logical(),
                        group = character(),
                        COMMON = character())

edge_final = data.frame(source = character(),
                        target = character(),
                        interaction = character(),
                        weight = numeric())

# Filtering the data to two column namely row_num and Ensembl to a new variable a
cd <- genedata[,c("row_num","Gene")]
# Merging two dataframes a and datExpr1 for getting the ensembl id to the datExp variable for pivoting
d <- merge(cd, datExpr1, by = "row_num")
# Dropping the row_num column
d <- d[,-1]
# Making the Ensembl column to naming the rows
rownames(d) <- d[,1]
# Dropping the Ensembl column for analysis
d <- d[,-1]
d <- d[,-1]
#Transposing the dataframe to desired format where gene instance are columns and samples are rows
Expr = as.data.frame(t(d))

########################## Export the data to cytoscape for Black module ################################################
for(col in colors){
  modules = col
  # Select module probes
  probes = names(Expr)
  inModule = is.finite(match(moduleColors, modules))
  modProbes = probes[inModule]
  modGenes = final$Gene_symbol[match(modProbes, final$Ensembl)]

  # Select the corresponding Topological Overlap
  modTom = TOM[inModule, inModule]
  dimnames(modTom) = list(modGenes, modGenes)

  #set the diagonal of matrix to zero - eliminate self-correlation
  modTom[row(modTom) == col(modTom) ] <- 0

  # Export the network into edge and node list files Cytoscape can read
  cyt = exportNetworkToCytoscape(modTom,
                                 edgeFile = file.path(cytoscape_dir,
                                   paste0("CytoscapeInput-edges-", paste(modules, collapse="-"), ".txt")),
                                 nodeFile = file.path(cytoscape_dir,
                                   paste0("CytoscapeInput-nodes-", paste(modules, collapse="-"), ".txt")),
                                 weighted = TRUE,
                                 threshold = 0.08,
                                 nodeNames = modGenes,
                                 altNodeNames = modProbes,
                                 nodeAttr = moduleColors[inModule])

  # Read the Nodes file for Cytoscape Network
  nodes = read.delim2(file = file.path(cytoscape_dir,
                        paste0("CytoscapeInput-nodes-", paste(modules, collapse="-"), ".txt")),
                      sep = "\t")
  nodes = cbind(nodes, nodes[,1])
  names(nodes) = c("id", "altName", "group", "COMMON")
  if(nrow(node_final)== 0){
    node_final = nodes
  }
  else{
    node_final = rbind(node_final,nodes)
  }

  # Read the edges file for the Cytoscape Network
  edges = read.delim2(file = file.path(cytoscape_dir,
                        paste0("CytoscapeInput-edges-", paste(modules, collapse="-"), ".txt")),
                      sep = "\t")
  edges = edges[,1:4]
  edges = edges[,c(1,2,4,3)]
  names(edges) = c("source", "target", "interaction", "weight")
  edges$weight = as.numeric(edges$weight)
  if(nrow(edge_final) == 0){
    edge_final = edges
  }
  else{
    edge_final = rbind(edge_final, edges)
  }
}
node_final = merge(node_final,final, by.x = "id", by.y = "Gene_symbol", all.x = T)

# ---- Cytoscape live-session steps (require running Cytoscape desktop) ----
if (!skip_cytoscape) {
  suppressPackageStartupMessages(library(RCy3))
  createNetworkFromDataFrames(node_final,edge_final, title=paste("Gene network",modules, "ALL", sep = " - "), collection=paste0("Final","_Network Collection"))

  createDegreeFilter('degree filter', c(0,2), 'IS_NOT_BETWEEN')
  createColumnFilter(filter.name = "ASD Filter", column = "ASD", criterion = 1,predicate = 'IS', network = paste("Gene network",modules, "ALL", sep = " - "))
  createColumnFilter(filter.name = "PMS Filter", column = "PMS", c(1,1), 'BETWEEN', network = paste("Gene network",modules, "ALL", sep = " - "))
  createCompositeFilter(filter.name = "ASD_PMS Filter", filter.list = c("ASD Filter", "PMS Filter"))

  createSubnetwork(nodes = node_final[node_final$ASD == 1 & node_final$PMS == 1,]$id, nodes.by.col = "id", edges = "all", network = paste("Gene network",modules, "ALL", sep = " - ") ,subnetwork.name = "Gene Network: ASD-PMS")

  node_ASD_PMS = node_final[node_final$ASD == 1 & node_final$PMS == 1,]

  disease_list = c("ASD","I_D","Seizures","Hypotonia","Lang_Imp")
  gene_annotation = final
  node_pms = node_final[node_final$id %in% gene_annotation[gene_annotation$PMS == 1,"Gene_symbol"] ,]
  rownames(node_pms) = seq(1:nrow(node_pms))
  edge_pms = edge_final[edge_final$source %in% gene_annotation[gene_annotation$PMS == 1,"Gene_symbol"],]
  rownames(edge_pms) = seq(1:nrow(edge_pms))

  for(dis in disease_list){
    t = gene_annotation[,c("Gene_symbol", dis)]
    t = t %>% filter(t[,2] == 1)
    edge_pms_temp = edge_pms[edge_pms$target %in% t[,"Gene_symbol"],]
    # Create network in Cytoscape using function in R
    if(nrow(node_pms) != 0 || nrow(edge_pms_temp) != 0){
      createNetworkFromDataFrames(node_pms,edge_pms_temp, title=paste("Gene network",paste(dis, collapse = "-"),sep = " - "), collection=paste0(dis," Network Collection"))
    }
  }
} else {
  message("Skipping live Cytoscape steps (--skip_cytoscape TRUE)")
}

########################## Export data for edges to generate supplemental table ################################################

color_list = unique(moduleColors[moduleColors != 'grey'])
for(i in color_list)
{
  # Select modules
  modules = i
  # Select module probes
  probes = names(datExpr)
  inModule = is.finite(match(moduleColors, modules))
  modProbes = probes[inModule]
  modGenes = final$Gene_symbol[match(modProbes, final$Ensembl)]
  # Select the corresponding Topological Overlap
  modTom = TOM[inModule, inModule]
  dimnames(modTom) = list(modProbes, modProbes)

  #set the diagonal of matrix to zero - eliminate self-correlation
  modTom[row(modTom) == col(modTom) ] <- 0

  # Export the network into edge and node list files Cytoscape can read
  cyt = exportNetworkToCytoscape(modTom,
                                 edgeFile = file.path(cytoscape_dir, "CytoscapeInput-edges-10_29_22.txt"),
                                 nodeFile = file.path(cytoscape_dir, "CytoscapeInput-nodes-10_29_22.txt"),
                                 weighted = TRUE,
                                 threshold = 0.1,
                                 nodeNames = modProbes,
                                 altNodeNames = modGenes,
                                 nodeAttr = moduleColors[inModule])

  # Read the Nodes file for Cytoscape Network
  nodes = read.delim2(file = file.path(cytoscape_dir, "CytoscapeInput-nodes-10_29_22.txt"))
  nodes = cbind(nodes, nodes[,1])
  names(nodes) = c("id", "altName", "group", "COMMON")

  # Read the edges file for the Cytoscape Network
  edges = read.delim2(file = file.path(cytoscape_dir, "CytoscapeInput-edges-10_29_22.txt"))
  edges = edges[,1:4]
  edges = edges[,c(1,2,4,3)]
  names(edges) = c("source", "target", "interaction", "weight")
  edges$weight = as.numeric(edges$weight)
}

# ---------------------------------------------------------------------------
# Save TOM objects for downstream ranking module
# ---------------------------------------------------------------------------
saveRDS(list(TOM = TOM, modTom = modTom, final = final,
             color_list = color_list, node_final = node_final, edge_final = edge_final),
        file.path(output_dir, "tom_objects.rds"))
message("Written: tom_objects.rds")
message("=== Module 3 complete ===")
